### ISSUE TITLE
Caught UnicodeDecodeError when use `parseToNode` alone

### ISSUE THREAD

**Issue by graph226** [SamuraiT/mecab-python3#3] opened 2016-11-14 08:10 UTC
When we use `tagger.parseToNode(text)` alone, sometimes we get such error as:

``` 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 1: invalid start byte
```

To avoid this, put `tagger.parse(text)` before parseToNode.

**Comment by graph226** [comment] 2016-11-14 08:14
For modifying this, we can call `parse` method before `parseToNode` but I don't know whether it works or not 😇 

https://github.com/SamuraiT/mecab-python3/blob/5ee7aa538c8408d61a42aedea9d2f000c86f1ca3/MeCab.py#L282

like

```
def parseToNode(self, *args):
    self.parse(self, *args)
    return _MeCab.Tagger_parseToNode(self, *args)
```

Please give me your idea about this.

**Comment by shiumachi** [comment] 2018-01-16 14:55
I got the same error and fixed it with the above workaround.

**Comment by kei-s** [comment] 2018-01-17 09:14
I investigated the reason of this bug.

In `_wrap_Tagger_parseToNode` method, this line deletes `buf2` because `alloc2` is `SWIG_NEWOBJ`.
https://github.com/SamuraiT/mecab-python3/blob/5ee7aa538c8408d61a42aedea9d2f000c86f1ca3/MeCab_wrap.cxx#L6527

In python 2, the `buf2` is not deleted because `alloc2` is `SWIG_OLDOBJ`.
(MeCab_wrap.cxx is completely same as original @taku910's one. https://github.com/taku910/mecab/blob/master/mecab/python/MeCab_wrap.cxx .)

So, the reason of this bug is in `SWIG_AsCharPtrAndSize` method.
I think this block has something wrong.
https://github.com/SamuraiT/mecab-python3/blob/5ee7aa538c8408d61a42aedea9d2f000c86f1ca3/MeCab_wrap.cxx#L3461-L3470
But I don't have the patch to solve this bug at this time. 😕

**Comment by orangain** [comment] 2018-03-21 08:35
I got the same problem and found that using the latest version of MeCab solves the problem.

My environment:

* OS: macOS High Sierra 10.13.3
* Python: 3.6.3
* mecab-python3: 0.7
* MeCab: 0.996 (**BUILT FROM SOURCE** https://github.com/taku910/mecab/commit/3a07c4eefaffb4e7a0690a7f4e5e0263d3ddb8a3)
---

This problem seems to be the same as the one reported in https://github.com/taku910/mecab/issues/5, and it has been solved by https://github.com/taku910/mecab/pull/24 merged in Feb 2016.

 Alhough this problem occurs only in Python 3, it is not a matter of mecab-python3, but it seems to be a matter of memory management of MeCab itself.

Unfortunately, major package managers such as [Homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/mecab.rb) and [APT](https://packages.debian.org/stable/mecab) currently offer older version of MeCab based on the source in Feb 2013, which can be obtained from Google Drive.

 To avoid this problem without using the workaround mentioned above, you need to build and install MeCab from the latest source on GitHub manually, and then reinstall mecab-python3.

**Comment by zackw** [comment] 2018-11-04 18:06
@graph226 I believe this ought to be fixed by using the latest version of the package and the latest version of MeCab, but I cannot be sure because you did not provide a complete test case that I can run for myself.  Could you please try your code again?  Make sure to use mecab-python3 0.8.3, MeCab 0.996, and a current version of SWIG (I have 3.0.12).

**Comment by polm** [comment] 2018-12-17 13:03
Please see the spaCy issue linked above, which provides a Dockerfile and code to reproduce the issue. I think @orangain's explanation is exactly right.

**Comment by zackw** [comment] 2018-12-17 16:58
@polm Thanks for the pointer.  I think you're right.  I am going to consider this bug a concrete reason why we need to ship binary wheels from PyPI with bundled libmecab, so it will be addressed by PR #18, which I will be reviewing and landing Real Soon Now.  I'll leave the bug open till then.

**Comment by zackw** [comment] 2019-04-16 19:09
Please try the release candidate available from https://test.pypi.org/project/mecab-python3/0.996.2rc2/ , this bug should be corrected.

**Comment by zackw** [comment] 2019-04-22 18:53
0.996.2 has been officially released and this issue should be corrected.  Please file a new bug report if you are still having problems with `parseToNode`.

**Closed by zackw** 2019-04-22 18:53 UTC
