### ISSUE TITLE
Recent change has caused parseToNode to have different behaviour

### ISSUE THREAD

**Issue by Denubis** [SamuraiT/mecab-python3#24] opened 2019-01-24 07:39 UTC
Running test.py returns:

~~~
brian@1602019:~/People/Chavalin/nlp-japanese$ python3 test.py
0.996
太郎	名詞,固有名詞,人名,名,*,*,太郎,タロウ,タロー
は	助詞,係助詞,*,*,*,*,は,ハ,ワ
この	連体詞,*,*,*,*,*,この,コノ,コノ
本	名詞,一般,*,*,*,*,本,ホン,ホン
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
二	名詞,数,*,*,*,*,二,ニ,ニ
郎	名詞,一般,*,*,*,*,郎,ロウ,ロー
を	助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
見	動詞,自立,*,*,一段,連用形,見る,ミ,ミ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
女性	名詞,一般,*,*,*,*,女性,ジョセイ,ジョセイ
に	助詞,格助詞,一般,*,*,*,に,ニ,ニ
渡し	動詞,自立,*,*,五段・サ行,連用形,渡す,ワタシ,ワタシ
た	助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
。	記号,句点,*,*,*,*,。,。,。
EOS

太郎はこの本を二郎を見た女性に渡した。 	 BOS/EOS,*,*,*,*,*,*,*,*
EOS
太郎はこの本を二郎を見た女性に渡した。 	 名詞,固有名詞,人名,名,*,*,太郎,タロウ,タロー
EOS
はこの本を二郎を見た女性に渡した。 	 助詞,係助詞,*,*,*,*,は,ハ,ワ
EOS
この本を二郎を見た女性に渡した。 	 連体詞,*,*,*,*,*,この,コノ,コノ
EOS
本を二郎を見た女性に渡した。 	 名詞,一般,*,*,*,*,本,ホン,ホン
EOS
を二郎を見た女性に渡した。 	 助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
EOS
二郎を見た女性に渡した。 	 名詞,数,*,*,*,*,二,ニ,ニ
EOS
郎を見た女性に渡した。 	 名詞,一般,*,*,*,*,郎,ロウ,ロー
EOS
を見た女性に渡した。 	 助詞,格助詞,一般,*,*,*,を,ヲ,ヲ
EOS
見た女性に渡した。 	 動詞,自立,*,*,一段,連用形,見る,ミ,ミ
EOS
た女性に渡した。 	 助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
EOS
女性に渡した。 	 名詞,一般,*,*,*,*,女性,ジョセイ,ジョセイ
EOS
に渡した。 	 助詞,格助詞,一般,*,*,*,に,ニ,ニ
EOS
渡した。 	 動詞,自立,*,*,五段・サ行,連用形,渡す,ワタシ,ワタシ
EOS
た。 	 助動詞,*,*,*,特殊・タ,基本形,た,タ,タ
EOS
。 	 記号,句点,*,*,*,*,。,。,。
EOS
 	 BOS/EOS,*,*,*,*,*,*,*,*
EOS
EOS
filename: /var/lib/mecab/dic/debian/sys.dic
charset: UTF-8
size: 392126
type: 0
lsize: 1316
rsize: 1316
version: 102
~~~

The parseToNode surface is displaying the entire remaining string.

**Comment by zackw** [comment] 2019-03-22 20:29
Indeed, duplicate of #19.  A fixed wheel will be available Real Soon Now.

**Closed by zackw** 2019-03-22 20:29 UTC
Labels: bug, duplicate

**Comment by zackw** [comment] 2019-04-16 19:14
Please try the release candidate available from https://test.pypi.org/project/mecab-python3/0.996.2rc2/ , this bug should be corrected. Thank you everyone for your patience. We plan to make a new official release in the next couple of weeks.
