### ISSUE TITLE
Error when processing with big dataset

### ISSUE THREAD

**Issue by bigredbug47** [SamuraiT/mecab-python3#63] opened 2021-04-07 08:30 UTC
Hi all,

Thanks for the awesome library. 🙇‍♂️🙇‍♂️🙇‍♂️

I try to tokenize my Japanese dataset but it occurred errors and seem it couldn't be used again if not force-reinstall the mecab-pyhton3 library and the unidic-lite.

Could you advise me how to solve my problem? Thank you. 🙏🙏🙏

Here is some errors I occurred when running Mecab through 70,000 sentences (in sequence): 🚩

```
Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -r /opt/conda/lib/python3.7/site-packages/unidic_lite/dicdir/mecabrc
error message: ) [tokenizer_->open(param)] tokenizer.cpp(105) [property_.open(param)] char_property.cpp(82) [cmmap_->open(filename, "r")]
```

```
error message: viterbi.cpp(54) [connector_->open(param)] connector.cpp(24) [cmmap_->open(filename, mode)] cannot open: /opt/conda/lib/python3.7/site-packages/unidic_lite/dicdir/matrix.bin
```

```
error message: viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(110) [sysdic->open (create_filename(prefix, SYS_DIC_FILE).c_str())] dictionary.cpp(79) [dmmap_->open(file, mode)] no such file or directory: /opt/conda/lib/python3.7/site-packages/unidic_lite/dicdir/
```

```
ImportError: /opt/conda/lib/python3.7/site-packages/MeCab/_MeCab.cpython-37m-x86_64-linux-gnu.so: cannot change memory protections
```

```
ImportError: /opt/conda/lib/python3.7/site-packages/MeCab/_MeCab.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object
```

Here is package version: 📚
```
mecab-python3==1.0.3
unidic-lite==1.0.8
```

**Comment by polm** [comment] 2021-04-07 13:04
Closing as a duplicate of https://github.com/polm/fugashi/issues/35. I'll reply there.

**Closed by polm** 2021-04-07 13:04 UTC
